### ISSUE TITLE
running out of memory while testtoll creating a report

### ISSUE THREAD

**Issue by Bibi0803** [ibissource/ibis-ladybug#170]
When testing an adapter where a zip is created of the report, the JVM runs out of memory.

`java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapCharBuffer.<init>(HeapCharBuffer.java:57)
	at java.nio.CharBuffer.allocate(CharBuffer.java:335)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:810)
	at nl.nn.testtool.MessageEncoderImpl.toString(MessageEncoderImpl.java:85)
	at nl.nn.ibistesttool.MessageEncoder.toString(MessageEncoder.java:71)
	at nl.nn.testtool.Checkpoint.setMessage(Checkpoint.java:165)
	at nl.nn.testtool.Report.addCheckpoint(Report.java:518)
	at nl.nn.testtool.Report.addCheckpoint(Report.java:454)
	at nl.nn.testtool.Report.checkpoint(Report.java:340)
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:287)
	at nl.nn.testtool.TestTool.startpoint(TestTool.java:418)
	at nl.nn.ibistesttool.Debugger.pipeInput(Debugger.java:111)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeInputOutputAbort(IbisDebuggerAdvice.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at nl.nn.adapterframework.processors.InputOutputPipeProcessor$$EnhancerBySpringCGLIB$$f28c7d9.processPipe(<generated>)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase$$Lambda$762/1551590262.apply(Unknown Source)
	at nl.nn.adapterframework.processors.ExceptionHandlingPipeProcessor.processPipe(ExceptionHandlingPipeProcessor.java:38)
	at nl.nn.adapterframework.processors.PipeProcessorBase.processPipe(PipeProcessorBase.java:49)
	at nl.nn.adapterframework.processors.PipeProcessorBase.lambda$processPipe$0(PipeProcessorBase.java:49)`

![image](https://user-images.githubusercontent.com/60199670/214836905-1e96c30c-8aad-40a4-91a8-af9ff075cc10.png)
[Pipeline HandleEmail.zip](https://github.com/ibissource/ibis-ladybug/files/10509255/Pipeline.HandleEmail.zip)

**Comment by jacodg** [comment]
I think the message is not processed by the F!F as a stream. Can you see whether you can get the F!F to process the message as a stream? You can contact me in case of any questions
