### ISSUE TITLE
IndexOutOfBoundsException when running iaf-test

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#60]
When running the larva tests of iaf-test, an IndexOutOfBoundsException occurs when running the ApiWsdlGenerator-tests

ibis-ladybug version 2.0.15-20210106.180557

stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 21, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at nl.nn.testtool.Report.addCheckpoint(Report.java:332)
	at nl.nn.testtool.Report.checkpoint(Report.java:276)
	at nl.nn.testtool.TestTool.checkpoint(TestTool.java:241)
	at nl.nn.testtool.TestTool.abortpoint(TestTool.java:507)
	at nl.nn.ibistesttool.Debugger.pipeLineAbort(Debugger.java:95)
	at nl.nn.ibistesttool.IbisDebuggerAdvice.debugPipeLineInputOutputAbort(IbisDebuggerAdvice.java:108)
```

**Comment by jacodg** [comment]
Fixed with commit 2395adae73fcca2259c9642bc86d3dc1727fb87a
