### ISSUE TITLE
With stub strategy "Always", reports seem to get corrupt

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/ibis-ladybug#80]
I do not understand what goes wrong. Here are the steps to reproduce:

1. Start the Frank!Runner with Frank https://github.com/ibissource/frank-manual/tree/master/srcSteps/ladybugInstance/v500. This URL has directories `classes` and `configurations`.
2. Run adapter sutArchive with input `<document>This is the document</document>`.
3. Go to Ladybug and press "Refresh". You see two reports with names "sutArchive" and "externalArchive".
4. Copy test report "externalArchive" with stub strategy "Always".
5. Go to tab "Test" and press "Refresh".
6. Select the new test report and press "Download All".
7. Stop the Frank!Runner.
8. Delete the "build" directory of the Frank!Runner.
9. Restart the Frank!Runner.
10. Go to tab "Test". The test report you created still exists.
11. Run the test report. You see a green text.
12. Press "Refresh". You have the following error:

![image](https://user-images.githubusercontent.com/6784732/144023000-bfca8fe9-1538-43b8-baf2-cd4c2c2e8958.png)

In the Catalina window produced by the Frank!Runner, there is no Java exception.

13. Remove the test report.
14. Upload test reports from the file you downloaded.

The report appears again, but there is an error as shown below.

![image](https://user-images.githubusercontent.com/6784732/144023716-eef8816c-2fd1-41c1-897b-f3db26dde8cd.png)

Before I did these steps, I did something similar. I was doing the Ladybug tutorial of the Frank!Manual, https://frank-manual.readthedocs.io/en/nojmsrealm/testing/ladybug/edit/edit.html. At that time, I saw the following Java exception in my Catalina window:

```
30-Nov-2021 10:12:24.747 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-80"]
30-Nov-2021 10:12:24.755 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [12999] milliseconds
30-Nov-2021 10:15:03.004 SEVERE [http-nio-80-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [TestToolServlet] in context with path [] threw exception
        java.lang.RuntimeException: java.lang.NullPointerException
                at nextapp.echo2.webcontainer.filetransfer.UploadSelectPeer.processFileUpload(UploadSelectPeer.java:121)
                at nextapp.echo2.webcontainer.filetransfer.UploadSelectPeer.processAction(UploadSelectPeer.java:104)
                at nextapp.echo2.webcontainer.ContainerSynchronizeService$2.process(ContainerSynchronizeService.java:181)
                at nextapp.echo2.webrender.service.SynchronizeService.processClientMessage(SynchronizeService.java:217)
                at nextapp.echo2.webcontainer.ContainerSynchronizeService.renderUpdate(ContainerSynchronizeService.java:469)
                at nextapp.echo2.webrender.service.SynchronizeService.service(SynchronizeService.java:279)
                at nextapp.echo2.webrender.WebRenderServlet.process(WebRenderServlet.java:273)
                at nextapp.echo2.webrender.WebRenderServlet.doPost(WebRenderServlet.java:189)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: java.lang.NullPointerException
                at nl.nn.testtool.storage.xml.XmlStorage.getReport(XmlStorage.java:156)
                at nl.nn.testtool.util.Import.importZip(Import.java:75)
                at nl.nn.testtool.echo2.util.Upload.upload(Upload.java:30)
                at nl.nn.testtool.echo2.reports.ReportUploadListener.fileUpload(ReportUploadListener.java:83)
                at nextapp.echo2.app.filetransfer.UploadSelect.fileUpload(UploadSelect.java:92)
                at nextapp.echo2.webcontainer.filetransfer.UploadSelectPeer.processFileUpload(UploadSelectPeer.java:117)
                ... 37 more
```

**Comment by jacodg** [comment]
Could it be the case that you are reading/using reports which have been created with a Ladybug version before https://github.com/ibissource/ibis-ladybug/commit/5d9c4b38468689d1c2d141760e7461ac3e3b6f2d?

**Comment by mhdirkse** [comment]
I did the steps again with a different result. After step 10 or 11, I got:

![image](https://user-images.githubusercontent.com/6784732/145024298-f1545406-abde-464e-ac15-38f81661bc33.png)

Then I tried to remove the report and upload it from the result of step 6. When I tried to run it, or maybe even before running, I saw the same error.

**Comment by mhdirkse** [comment]
I made an error when I wrote this issue. Step 4 says: "Copy test report "externalArchive" with stub strategy "Always".". This should be copying adapter sutArchive. In the test of the above comment, I copied the sutArchive report.

**Comment by jacodg** [comment]
I think you need to remove the Ladybug storage files from the log dir and have Ladybug create the files again
